export let moviesList = [
  {
    id: "1",
    title: "John Wick: Part 4 John Wick: Part 4",
    overview: "Some quick example text to build on the card",
    genre: "Action",
    liked: false,
    rating: 9.2,
    year: "2023",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "2",
    title: "nvkj",
    overview: "Some quick example text to build on the card",
    genre: "Romance",
    liked: false,
    rating: 8,
    year: "2019",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "3",
    title: "lbri",
    text: "Some quick example text to build on the card",
    genre: "Action",
    liked: false,
    rating: 5.1,
    year: "2022",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "4",
    title: "angks",
    overview: "Some quick example text to build on the card",
    genre: "Drama",
    liked: false,
    rating: 4.6,
    year: "2023",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "5",
    title: "Lucey",
    overview: "Some quick example text to build on the card",
    genre: "Romance",
    liked: false,
    rating: 9.2,
    year: "2023",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "6",
    title: "Mdwwe 2",
    overview: "Some quick example text to build on the card",
    genre: "Action",
    liked: false,
    rating: 8,
    year: "2012",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "7",
    title: "Obhde",
    overview: "Some quick example text to build on the card",
    genre: "Horror",
    liked: false,
    rating: 5.1,
    year: "2022",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "8",
    title: "peir 4",
    overview: "Some quick example text to build on the card",
    genre: "Action",
    liked: false,
    rating: 4.6,
    year: "2023",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
];

export const genresList = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "History",
  "Horror",
  "Music",
  "Mystery",
  "Romance",
  "Science Fiction",
  "Thriller",
  "War",
  "Western",
];

export const sidebarList = [
  {
    title: "Genre",
    data: [
      "Action",
      "Adventure",
      "Animation",
      "Comedy",
      "Crime",
      "Documentary",
      "Drama",
      "Family",
      "Fantasy",
      "History",
      "Horror",
      "Music",
      "Mystery",
      "Romance",
      "Science Fiction",
      "Thriller",
      "War",
      "Western",
    ],
  },
  // {
  //   title: "Year",
  //   data: ["2023", "2022", "2021", "2020", "2019", "2018"],
  // },
  // {
  //   title: "Rating",
  //   data: [9, 8, 7, 6, 5, 4],
  // },
];

export const bannerMovies = [
  {
    id: "1",
    title: "John Wick: Chapter 4",
    overview:
      "Some quick example text to build on the card Some quick example text to build on the card",
    genre: "Action",
    liked: false,
    rating: 9.2,
    year: "2023",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "2",
    title: "Some Quick",
    overview:
      "Some quick example text to build on the card Some quick example text to build on the card",
    genre: "Romance",
    liked: false,
    rating: 8,
    year: "2019",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
  {
    id: "3",
    title: "Fawd Kwidiw Lik",
    overview:
      "Some quick example text to build on the card Some quick example text to build on the card",
    genre: "Action",
    liked: false,
    rating: 5.1,
    year: "2022",
    poster_path: "../../../assets/images/john_wick.jpg",
    banner_path: "../../../assets/images/john_wick_banner.jpeg",
  },
];

export const users = [
  {
    id: "1",
    firstName: "Rhafln",
    lastName: "Ghalio",
    password: "2525",
    email: "admin@admin.com",
  },
];
